= Semestral work from NI-PYT in 2020/21 at https://old.fit.cvut.cz/en[FIT CTU]

* CTU username: `saframa6`
* CTU mail: saframa6@fit.cvut.cz

⚠️ Currently waiting for the API key from https://beta.openai.com/?demo=5[Academic Access Application] to access GPT-3. In case it will not be granted or will be granted later, <<alternative>> will be considered as an output of my semestral work.

== Topic 1: TEXT to HTML translation using GPT-3

=== Goal

In this work, I use https://en.wikipedia.org/wiki/GPT-3[GPT-3] to translate arbitrary input text to HTML. Example output might look like https://twitter.com/sharifshameem/status/1282676454690451457[this].

=== Requirements for grading

1. Use `requests` for communicating with GPT-3 API
2. Create command line interface that accepts input text and produces HTML
3. Load configuration from file using `configparser`, at least allowing to use own GPT-3 API key
4. Write tests using `pytest`, but also allow to run them using `tox`
	. Fake GPT-3 API using `betamax`
	. Internal functionality
5. Make it available on Pypi as a package
6. Document project using docstrings in code and this README
7. Create GUI using `PySide`, which in addition to the CLI interface renders HTML output and displays it to the user

[#alternative]
== Topic 2: GitLab to GitHub project export

=== Goal
Sometimes I need to export projects from FIT CTU GitLab to GitHub. It can be done https://stackoverflow.com/a/22266000/6784881[manually], but for a larger amount of projects, it is very time-consuming. For example, if you finish your studies at FIT CTU, you immediately lose access to your GitLab and all of your projects (even if you continue your studies, in a meantime you lose access).

=== Known issues
1. Synchronization of big files. FIT CTU GitLab allows files bigger than 200MB to be stored. GitHub does not. Git LFS can be used instead.
2. Access control works differently in GitLab and GitHub


=== Requirements for grading
. Use `requests` for communicating with GitLab and GitHub API
. Use some python git wrapper or git directly to manipulate with cloned repositories (eg setting different upstream)
. Create command line interface, which will at least allow
	.. Specify a list of repository names for exporting
	.. Set policy for conflicts, eg project with the same name already exists on GitHub => overwrite
. Inform user about the exporting process by terminal output and also store this information in logs
. Load configuration from a file using `configparser`, at least allowing to use own API keys
. Write tests using `pytest`, but also allow to run them using `tox`
	.. Fake both API for testing
	.. Test internal functionality
. Make it available on Pypi
. Document project using docstrings in code and this README
