= Semestral work from NI-PYT in 2020/21 at https://old.fit.cvut.cz/en[FIT CTU]

* CTU username: `saframa6`
* CTU mail: saframa6@fit.cvut.cz

⚠️ Currently waiting for the API key from https://beta.openai.com/?demo=5[Academic Access Application] to access GPT-3. In case it will not be granted or will be granted later, <<alternative>> will be considered as an output of my semestral work.

== TEXT to HTML translation using GPT-3

=== Goal

In this work, I use https://en.wikipedia.org/wiki/GPT-3[GPT-3] to translate arbitrary input text to HTML. Example output might look like https://twitter.com/sharifshameem/status/1282676454690451457[this].

=== Requirements for grading

1. Use `requests` for communicating with GPT-3 API
2. Create command line interface that accepts input text and produces HTML
3. Load configuration from file using `configparser`, at least allowing to use own GPT-3 API key
4. Write tests using `pytest`, but also allow to run them using `tox`
	. Fake GPT-3 API using `betamax`
	. Internal funcionality
5. Make it availible on Pypi as a package
6. Document project using docstrings in code and this README
7. Create GUI using `PySide`, which in addition to the CLI interface renders HTML output and displays it to the user

[#alternative]
== Alternative
TBA

=== Goal

=== Requirements for grading

